version: '3.3'

networks:
  mynetwork:
    driver: bridge


services:
  # PostgreSQL service
  database:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data 
    networks:
      - mynetwork
    container_name: postgres_container_video

  # Django service
  django:
    build:
      context: backend/.
      dockerfile: Dockerfile
    image: video_transriber_backend_image
    privileged: true
    env_file: .env
    depends_on:
      - database
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    volumes:
      - ./backend:/app  # Mount your project directory to the /app directory in the container
    container_name: django_container_video

  react_frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    image: video_transcriber_frontend_image
    environment: 
      - REACT_APP_URL=http://django:8000/
    ports:
      - "5000:5000"
    networks: 
      - mynetwork
    volumes:
      - ./frontend:/app/frontend/
    depends_on:
      - django
    container_name: react_container_video
      # Nginx service for HLS streaming

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/media/hls:/usr/share/nginx/html/hls
    networks:
      - mynetwork
    container_name: nginx_container_video

  link_frontend:
    image: fractalnetworks/gateway-client:latest
    environment:
      LINK_DOMAIN: meet.fractalnetworks.co
      EXPOSE: react_frontend:5000
      GATEWAY_CLIENT_WG_PRIVKEY: OH6MeF1SvGXM/CMGJUJR1y0r7IyNb9r0Ro+g3A4MsEI=
      GATEWAY_LINK_WG_PUBKEY: QO3RkPFa5mybaRiV6MTVqISN2f+FNcflrXRx7370Wio=
      GATEWAY_ENDPOINT: 167.235.132.246:32768
    networks:
      - mynetwork
    cap_add:
      - NET_ADMIN
  link_backend:
    image: fractalnetworks/gateway-client:latest
    environment:
      LINK_DOMAIN: api.meet.fractalnetworks.co
      EXPOSE: django:8000
      GATEWAY_CLIENT_WG_PRIVKEY: OO5j/mI9LJFlNLpe2KOqEIVE0KND2N/B0OK8deztynA=
      GATEWAY_LINK_WG_PUBKEY: GdxLSJBnQHHYG/T3HGHWh1QJbJiXhZPwBFX34bijqQU=
      GATEWAY_ENDPOINT: 167.235.132.246:32770
    networks:
      - mynetwork
    cap_add:
      - NET_ADMIN

  link_nginx:
    image: fractalnetworks/gateway-client:latest
    environment:
      LINK_DOMAIN: app.meet.fractalnetworks.co
      EXPOSE: nginx:80
      GATEWAY_CLIENT_WG_PRIVKEY: SKlWH2Qsq8n/5GBoYihAOSYKIZl8ouRtV3/zpvHMXVw=
      GATEWAY_LINK_WG_PUBKEY: CmtxVjYsPP3+R3QUWIGWNS+onQqf/XasbPm0AQMQfig=
      GATEWAY_ENDPOINT: 167.235.132.246:32771
    networks:
      - mynetwork
    cap_add:
      - NET_ADMIN
