version: '3.3'

networks:
  mynetwork:
    driver: bridge
volumes:
  link_frontend:
  link_backend:
  link_nginx:


services:
  # PostgreSQL service
  database:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data 
    networks:
      - mynetwork
    container_name: postgres_container_video

  # Django service
  django:
    build:
      context: backend/.
      dockerfile: Dockerfile
    image: video_transriber_backend_image
    privileged: true
    env_file: .env
    depends_on:
      - database
    networks:
      - mynetwork
    volumes:
      - ./backend:/app  # Mount your project directory to the /app directory in the container
    container_name: django_container_video

  react_frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    image: video_transcriber_frontend_image
    env_file:
      - .env
    networks: 
      - mynetwork
    volumes:
      - ./frontend:/app/frontend/
    ports:
      - "5000:5000"
    depends_on:
      - django
    container_name: react_container_video
      # Nginx service for HLS streaming

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/media/hls:/usr/share/nginx/html/hls
      - ./backend/media/video:/usr/share/nginx/html/videos
    networks:
      - mynetwork
    container_name: nginx_container_video

  link_frontend:
    image: fractalnetworks/gateway-client:latest
    env_file: 
      - .env.frontend
    networks:
      - mynetwork
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  link_nginx:
    image: fractalnetworks/gateway-client:latest
    env_file:
      - .env.nginx
    networks:
      - mynetwork
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  link_backend:
    image: fractalnetworks/gateway-client:latest
    env_file:
      - .env.backend
    networks:
      - mynetwork
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
