version: '3.3'

networks:
  mynetwork:
    driver: bridge
volumes:
  link_frontend:
  link_backend:
  link_nginx:


services:
  # PostgreSQL service
  database:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data 
    networks:
      - mynetwork
    container_name: postgres_container_video

  # Django service
  django:
    build:
      context: backend/.
      dockerfile: Dockerfile
    image: video_transriber_backend_image
    privileged: true
    env_file: .env
    depends_on:
      - database
    networks:
      - mynetwork
    volumes:
      - ./backend:/app  # Mount your project directory to the /app directory in the container
    container_name: django_container_video

  react_frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    image: video_transcriber_frontend_image
    environment: 
      - REACT_APP_URL=http://django:8000/
    networks: 
      - mynetwork
    volumes:
      - ./frontend:/app/frontend/
    ports:
      - "5000:5000"
    depends_on:
      - django
    container_name: react_container_video
      # Nginx service for HLS streaming

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/media/hls:/usr/share/nginx/html/hls
    networks:
      - mynetwork
    container_name: nginx_container_video

  link_frontend:
    image: fractalnetworks/gateway-client:latest
    environment:
      LINK_DOMAIN: test.fractalnetworks.co
      EXPOSE: react_frontend:5000
      GATEWAY_CLIENT_WG_PRIVKEY: AMuk8o8Sj1iZ8IGSumccVTuxKkDkBTmiCRbQsnlGMGQ=
      GATEWAY_LINK_WG_PUBKEY: 2ZseM+CKfU1E6yI5AfRh0+A7XGFfJV6uS4jCkL3sKQI=
      GATEWAY_ENDPOINT: 195.201.1.131:32788
      # Remove following to disable basic authentication
      # Remove following line to get certs from Let's Encrypt
      #
      TLS_INTERNAL: true
      # CADDY_TLS_PROXY: true
      # CADDY_TLS_INSECURE: true
      # FORWARD_ONLY: true
    networks:
      - mynetwork
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  link_nginx:
    image: fractalnetworks/gateway-client:latest
    environment:
      LINK_DOMAIN: app.test.fractalnetworks.co
      EXPOSE: nginx:80
      GATEWAY_CLIENT_WG_PRIVKEY: yDx53zDmh3lc3FaxVjLFsgFLC+1Hv1ieDalWPtM5Xlw=
      GATEWAY_LINK_WG_PUBKEY: Xdrhdbb8ePxUyqY8gTLcM7RxZAteqQNczNj+//NHbV0=
      GATEWAY_ENDPOINT: 195.201.1.131:32791
      # Remove following to disable basic authentication
      #BASIC_AUTH: admin:admin
      # Remove following line to get certs from Let's Encrypt
      TLS_INTERNAL: true
      # CADDY_TLS_PROXY: true
      # CADDY_TLS_INSECURE: true
      # FORWARD_ONLY: true
    networks:
      - mynetwork
    restart: unless-stopped
    cap_add:
      - NET_ADMIN

  link_backend:
    image: fractalnetworks/gateway-client:latest
    environment:
      LINK_DOMAIN: api.test.fractalnetworks.co
      EXPOSE: django:8000
      GATEWAY_CLIENT_WG_PRIVKEY: MFKTqBbrqr9aNaY+ZZ6kPgLs3AhTOhtk9+v170pYmlY=
      GATEWAY_LINK_WG_PUBKEY: HxF5YldhqYEGLS04Febup8vqqIwJVtS9W2/24JOSwjs=
      GATEWAY_ENDPOINT: 195.201.1.131:32790
      # Remove following to disable basic authentication
      #BASIC_AUTH: admin:admin
      # Remove following line to get certs from Let's Encrypt
      TLS_INTERNAL: true
      # CADDY_TLS_PROXY: true
      # CADDY_TLS_INSECURE: true
      # FORWARD_ONLY: true
    networks:
      - mynetwork
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
