version: '3.3'

networks:
  mynetwork:
    driver: bridge
volumes:
  link_frontend:
  link_backend:
  link_nginx:


services:
  # PostgreSQL service
  database:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data 
    networks:
      - mynetwork
    container_name: postgres_container_video

  # Django service
  django:
    build:
      context: backend/.
      dockerfile: Dockerfile
    image: video_transriber_backend_image
    privileged: true
    env_file: .env
    depends_on:
      - database
    networks:
      - mynetwork
    volumes:
      - ./backend:/app  # Mount your project directory to the /app directory in the container
    container_name: django_container_video

  react_frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    image: video_transcriber_frontend_image
    environment: 
      - REACT_APP_URL=http://django:8000/
    networks: 
      - mynetwork
    volumes:
      - ./frontend:/app/frontend/
    depends_on:
      - django
    container_name: react_container_video
      # Nginx service for HLS streaming

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/media/hls:/usr/share/nginx/html/hls
    networks:
      - mynetwork
    container_name: nginx_container_video
  link_frontend:
    image: fractalnetworks/gateway-client:latest
    environment:
      LINK_DOMAIN: test.fractalnetworks.co
      EXPOSE: react_frontend:5000
      GATEWAY_CLIENT_WG_PRIVKEY: aBTbAkY9bdUMC/cQ9xZKvicUyz3G4LZqmOBFobPrmXY=
      GATEWAY_LINK_WG_PUBKEY: QXqO6OAFBk37m3O1KQhcRyZ16ioq7WtPeRvcdsFr424=
      GATEWAY_ENDPOINT: 195.201.1.131:32774
      BASIC_AUTH: fractal:fractalnetworksusb33java
    cap_add:
      - NET_ADMIN
    networks:
      - mynetwork
    volumes:
      - link_frontend:/root/.local/share/caddy
  link_backend:
    image: fractalnetworks/gateway-client:latest
    environment:
      LINK_DOMAIN: api.test.fractalnetworks.co
      EXPOSE: django:8000
      GATEWAY_CLIENT_WG_PRIVKEY: CLW4iFDXNP2suztmNO9Ov2NzI+qVDU41RNfh1tzW7V0=
      GATEWAY_LINK_WG_PUBKEY: wVruQlAtmVNSCvXSMnsO+IQAA45utof3LBzJ17dVjQM=
      GATEWAY_ENDPOINT: 195.201.1.131:32773
    cap_add:
      - NET_ADMIN
    networks:
      - mynetwork
    volumes:
      - link_backend:/root/.local/share/caddy
  link_nginx:
    image: fractalnetworks/gateway-client:latest
    environment:
      LINK_DOMAIN: app.test.fractalnetworks.co
      EXPOSE: nginx:80
      GATEWAY_CLIENT_WG_PRIVKEY: wOIIYxxDUE8GW/Y6g00HLgtjPJPuj3xcTrhzF8rG10k=
      GATEWAY_LINK_WG_PUBKEY: pEetLPkRoBCuOlgFGnTXwKNtSdyY4tc8XY2M73WMzFk=
      GATEWAY_ENDPOINT: 195.201.1.131:32772
    cap_add:
      - NET_ADMIN
    networks:
      - mynetwork
    volumes:
      - link_nginx:/root/.local/share/caddy
